### ISSUE TITLE
dataStream 理论上会导致溢出

### ISSUE THREAD

**Issue by xingrz** [iwillwen/node-qiniu#20]
粗略看了一下，依赖了你自己写的 dataStream 模块。[Stream](https://nodejs.org/docs/latest/api/stream.html) 本身的目的就是让数据更快地被下游使用，但是 dataStream 的实现却会把这个 stream 的数据全部缓存起来给 `.body()` 方法使用。可能会导致溢出哦。。。

**Comment by iwillwen** [comment]
Fixed in @6.1.9
