### ISSUE TITLE
如何获取下载外链

### ISSUE THREAD

**Issue by Kensuke-Hinata** [iwillwen/node-qiniu#25]
asset.url
asset.entryUrl
asset.download
都没有得到我要的外链

**Comment by iwillwen** [comment]
`asset.url()` 這是一個方法，不是一個直接的屬性

**Comment by Kensuke-Hinata** [comment]
哦哦，我试过的，不是我要的那个链接，不过最后发现private domain + key name就是我要的下载链接了。
